### ISSUE TITLE
Git patch files not working

### ISSUE THREAD

**Issue by BojanZelic** [tomzx/php-code-coverage-verifier#6]
Hello,

I've tried to use your library but it looks like whenever I generate a git diff file the UnifiedDiffParser class doesn't parse some lines correctly. In addition it looks like the clover.xml parser doesn't parse namespaced files.

I've attempted to fix the issues in this pull request.
https://github.com/tomzx/php-code-coverage-verifier/pull/5

**Comment by tomzx** [comment]
Closed with #5.
