### ISSUE TITLE
Permissions are incorrect on bin/php-code-coverage

### ISSUE THREAD

**Issue by BojanZelic** [tomzx/php-code-coverage-verifier#7]
Running a ```composer install``` with the package as a dependency (after the package has been updated) gives me this message.

```
Updating tomzx/php-code-coverage-verifier dev-master (d46343a => 315eb09)
    The package has modified files:
    M bin/php-code-coverage-verifier
    Discard changes [y,n,v,d,s,?]?
```

This is because the permissions on the file are set to `644` but they should be `755`

**Comment by tomzx** [comment]
Done @ 2485d56db6018cbb26803a74d62f5cf493e696d4.
